"""addLinkTable

Revision ID: 60adbded98b5
Revises: 238bc3b72dc6
Create Date: 2023-10-19 13:56:25.852155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60adbded98b5'
down_revision: Union[str, None] = '238bc3b72dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order', sa.String(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('order'),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link', schema='content')
    # ### end Alembic commands ###
